- name: Demo on loops
  hosts: local host
  connection: local
  tasks:
    - name: loops
      ansible.builtin.debug:
        msg: Student name is {{person}}
      loop:
        - Anusha
        - Govindaswamy

- name: Demo on loops other example
  hosts: local host
  connection: local
  tasks:
    - name: loops
      ansible.builtin.debug:
        msg: Student name is {{person.name}},age is {{person.age}}
      loop:
         - {name: Anusha, age: 26}
         - {name: Govindaswamy, age: 27}


- name: Demo on Loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo task for loop
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - apple
        - banana

    - name: Demo task for loop 2
      ansible.builtin.debug:
        msg: Fruit Name - {{ item.name }}, Quantity - {{ item.quantity }}
      loop:
        - {name: apple, quantity: 10}
        - {name: banana, quantity: 20}
