#TO PRINT
- name: to print something
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Print Hello Anusha
      ansible.builtin.debug:
        msg: Anusha learning Devops
#TO Install yum module related things
#To Execute shell commands
#To import tasks
#To import role
#To copy files
#To change the working directory and execute
#When condition
#blocks
#To create user
#to create directory
#To clean old app content
#To download and unarchieve app content