#TO PRINT
- name: to print something
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Print Hello Anusha
      ansible.builtin.debug:
        msg: Anusha learning Devops
#TO Install yum module related things

#To Execute shell commands
#To import tasks
- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml


#To import role
- name: Import Common NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
#To copy files
- name: Copy roboshop Config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
#To change the working directory and execute
- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app
#When condition
#blocks
- name: Load MySQL Schema
  when: schema_setup == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.yum:
        name: mysql

    - name: Load Schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', '{{ env }}.{{ component }}.db_host', region='us-east-1' ) }}  -u{{ lookup('aws_ssm', '{{ env }}.shipping.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', '{{ env }}.shipping.db_pass', region='us-east-1' ) }} < /app/schema/{{component}}.sql


#To create user
- name: Create Application User
  ansible.builtin.user:
    name: "anusha"
#to create directory
- name: Create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
#To clean old app content
- name: Clean Old App content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
#To download and unarchieve app content
- name: Download App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes