- name: Demo on playlevel variables
  hosts: all
  vars:
    URL: www.google.com
  tasks:
    - name: aceesing url
      ansible.builtin.debug:
        msg: Hello Anusha play level variables {{URL}}
#variable can be accesed at play level
- name: Demo on tasklevel variables
  hosts: all
  tasks:
    - name: aceesing url
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: www.sample.com
        #variable can be accesed at TASK level

