- name: Demo on playlevel variables
  hosts: all
  vars:
    URL: www.google.com
  tasks:
    - name: aceesing url
      ansible.builtin.debug:
        msg: Hello Anusha play level variables {{URL}}
        # In Ansible variable will be accessed using {{ }} ,
        # Ansible Supports double quotes and single quotes also , However quotes are  not mandatory in all cases
        # quotes are mandatory if value starts with a variable , meaning
        # msg: {{ URL }} <- This requires quoting
        # msg: URL - {{ URL }} <- This does not require quoting

#variable can be accesed at play level
- name: Demo on tasklevel variables
  hosts: all
  tasks:
    - name: aceesing url
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: www.sample.com
#variable can be accesed at TASK level
#Accessing variables at File level using vars_files
#vars_files supports only at play level but not at task level
- name: Demo on vars_files play level variables
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: aceesing url
      ansible.builtin.debug:
        msg: Hello Anusha play level variables {{URL}}
#variable can be accesed at play level for Roles
- name: Demo on playlevel variables for Roles
  hosts: all
  vars:
    URL: www.rolesplaylevel.com
  roles:
    -practice
#register level variable
- name: Demo on register level
  hosts: all
  tasks:
    - name: shell
      ansible.builtin.shell: uptime
      register: output
    - name: print
      ansible.builtin.debug :
        msg: "{{output}}"






